# Generated by Django 3.2.2 on 2021-06-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='city',
            field=models.CharField(default='add city', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='state',
            field=models.CharField(default='add state', max_length=100),
            preserve_default=False,
        ),
    ]
