# Generated by Django 3.2.2 on 2021-06-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_api', '0002_auto_20210626_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionmodel',
            name='fifth_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='descriptionmodel',
            name='fourth_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='descriptionmodel',
            name='third_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
