# Generated by Django 3.2.2 on 2021-06-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description_api', '0003_auto_20210626_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='state',
        ),
    ]
