# Generated by Django 3.2.2 on 2021-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_api', '0004_auto_20210626_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
