# Generated by Django 3.2.2 on 2021-07-27 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('description_api', '0005_alter_userprofilemodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionmodel',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
