# Generated by Django 3.2.2 on 2021-08-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description_api', '0006_descriptionmodel_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptionmodel',
            old_name='Plant_Name',
            new_name='plant_name',
        ),
    ]
