# Generated by Django 3.2.2 on 2021-08-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_api', '0007_rename_plant_name_descriptionmodel_plant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionmodel',
            name='favourite',
        ),
        migrations.AlterField(
            model_name='descriptionmodel',
            name='description',
            field=models.CharField(blank=True, help_text='Short and Concise', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionmodel',
            name='plant_name',
            field=models.CharField(help_text='Capital first letter,Like Rose', max_length=100),
        ),
    ]
