# Generated by Django 3.2.2 on 2021-08-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description_api', '0008_auto_20210817_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionmodel',
            name='fifth_image',
        ),
        migrations.RemoveField(
            model_name='descriptionmodel',
            name='first_image',
        ),
        migrations.RemoveField(
            model_name='descriptionmodel',
            name='fourth_image',
        ),
        migrations.RemoveField(
            model_name='descriptionmodel',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='descriptionmodel',
            name='third_image',
        ),
        migrations.CreateModel(
            name='DescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.ImageField(upload_to='media/')),
                ('second_image', models.ImageField(upload_to='media/')),
                ('third_image', models.ImageField(null=True, upload_to='media/')),
                ('fourth_image', models.ImageField(null=True, upload_to='media/')),
                ('fifth_image', models.ImageField(null=True, upload_to='media/')),
                ('image_for', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='description_api.descriptionmodel')),
            ],
        ),
    ]
