# Generated by Django 3.2.2 on 2021-08-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description_api', '0009_auto_20210818_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionimage',
            name='image_for',
        ),
    ]
