# Generated by Django 3.2.2 on 2021-08-18 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('description_api', '0010_remove_descriptionimage_image_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionmodel',
            name='image_for',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='description_api.descriptionimage'),
            preserve_default=False,
        ),
    ]
