# Generated by Django 3.2.2 on 2021-08-18 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('description_api', '0011_descriptionmodel_image_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionmodel',
            name='image_for',
        ),
        migrations.AddField(
            model_name='descriptionmodel',
            name='fifth_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='descriptionmodel',
            name='first_image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptionmodel',
            name='fourth_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='descriptionmodel',
            name='second_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptionmodel',
            name='third_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='DescriptionImage',
        ),
    ]
