# Generated by Django 3.2.2 on 2021-08-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_api', '0012_auto_20210818_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionmodel',
            name='city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='descriptionmodel',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
